spring.application.name=demo

spring.mongodb.uri=mongodb://localhost:27017/prueba_proyecto

#JWT
application.security.jwt.secret=${JWT_SECRET}
application.security.jwt.secret-key=${JWT_SECRET}

server.port=8082